run:
  tests: false
  skip-dirs:
    - ignite/ui
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - maligned
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    # - wsl
    - nolintlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
