builds:
  - main: ./starport/cmd/starport
    ldflags:
      - -s -w -X github.com/tendermint/starport/starport/version.Version={{.Tag}} -X github.com/tendermint/starport/starport/version.Date={{.Date}} -X github.com/tendermint/starport/starport/version.Head={{.FullCommit}}
    goarch:
      - amd64
changelog:
  skip: true
release:
  prerelease: true
