builds:
  - main: ./starport/cmd/starport
    ldflags:
      - -s -w -X github.com/ignite-hq/cli/ignite/internal/version.Version={{.Tag}} -X github.com/ignite-hq/cli/ignite/internal/version.Date={{.Date}}
    goarch:
      - amd64
