# run unit tests for Starport.
name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: go test -v ./...
