name: Lint

on:
  pull_request:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          install-mode: goinstall
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
