name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
          cache-dependency-path: go.sum

      - run: ./scripts/test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
          verbose: true
