name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          go-version: 1.19
      - run: ./scripts/test-unit
