name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum

      - run: ./scripts/test-coverage
        if: env.GIT_DIFF

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: env.GIT_DIFF
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
          verbose: true
